<?php

/**
 * Field definition is moved to a seperate module in order to be able to disable
 * modules that implements the field.
 * see http://drupal.org/node/1285540
 */


/**
 * Implements hook_field_info().
 */
function bibdk_sbkopi_field_field_info() { 
  return array(    
    'bibdk_sbkopi_link' => array(
      'label' => t('sbkopi link'),
      'description' => t('Link to reservation of articles'),
      'default_widget' => 'hidden',
     // 'default_widget' => 'text_textfield',
      'default_formatter' => 'bibdk_sbkopi_link_default',
      'no_ui' => TRUE,
    ),
  );
}

function bibdk_sb_kopi_add_js(){
  static $done;
  if (!isset($done)) {
    drupal_add_js('js/ajaxGetCopyOptions.js');
    $done = 1;
  }
}

/**
 * Implements hook_field_load().
 */
function bibdk_sbkopi_field_field_load($entity_type, $entities, $field, $instances, $langcode, &$items, $age) {
  bibdk_sb_kopi_add_js();
    
  foreach ($entities as $id => $entity) {
    $items[$id][] = array(
      'id' => $id,  
    );
  }
}

